service: github-webhook-listener

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    GITHUB_WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    JIRA_USER: ${env:JIRA_USER}
    JIRA_PASS: ${env:JIRA_PASS}

functions:
  githubWebhookListener:
    handler: handlers/github/index.githubWebhookListener
    events:
      - http:
          path: github/webhook
          method: post
          cors: true
  getJiraIssue:
    handler: handlers/jira/index.getIssue
    events:
      - http:
          path: jira/issue
          method: get
          cors: true
          request:
            parameters:
              key: true

