service: github-webhook-listener

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: '*'
  environment:
    GITHUB_WEBHOOK_SECRET: ${env:WEBHOOK_SECRET}
    JIRA_USER: ${env:JIRA_USER}
    JIRA_PASS: ${env:JIRA_PASS}
    GH_TOKEN: ${env:GH_TOKEN}

functions:
  githubWebhookListener:
    handler: handlers/github/index.githubWebhookListener
    events:
      - http:
          path: github/webhook
          method: post
          cors: true

